# Generated by Django 5.1.5 on 2025-02-12 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAuthe', '0014_alter_projectmembers_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='userAuthe.studentproject')),
                ('student_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuthe.studentlead')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='userAuthe.supervisor')),
            ],
            options={
                'ordering': ('-modified_at',),
            },
        ),
    ]
