# Generated by Django 5.1.5 on 2025-02-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='project',
        ),
    ]
