# Generated by Django 5.1.5 on 2025-02-03 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthe', '0002_studentlead_first_name_studentlead_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='student_lead',
        ),
        migrations.RemoveField(
            model_name='studentlead',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentlead',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='studentmember',
            name='project',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='last_name',
        ),
        migrations.CreateModel(
            name='StudentLeadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='userAuthe.studentlead')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='student_lead_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='userAuthe.studentleadprofile'),
        ),
        migrations.AddField(
            model_name='studentmember',
            name='student_lead_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='userAuthe.studentleadprofile'),
        ),
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='userAuthe.supervisor')),
            ],
        ),
    ]
