# Generated by Django 5.1.5 on 2025-02-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthe', '0003_remove_project_student_lead_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='student_lead_profile',
            new_name='studentleadprofile',
        ),
        migrations.RenameField(
            model_name='studentleadprofile',
            old_name='student_lead',
            new_name='studentlead',
        ),
        migrations.RenameField(
            model_name='studentmember',
            old_name='student_lead_profile',
            new_name='studentleadprofile',
        ),
    ]
