# Generated by Django 5.1.5 on 2025-02-03 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthe', '0004_rename_student_lead_profile_project_studentleadprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='studentleadprofile',
        ),
        migrations.RemoveField(
            model_name='studentmember',
            name='studentleadprofile',
        ),
        migrations.RemoveField(
            model_name='supervisorprofile',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='project',
            name='student_lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='userAuthe.studentlead'),
        ),
        migrations.AddField(
            model_name='studentmember',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='userAuthe.project'),
        ),
        migrations.DeleteModel(
            name='StudentLeadProfile',
        ),
        migrations.DeleteModel(
            name='SupervisorProfile',
        ),
    ]
