# Generated by Django 5.1.5 on 2025-02-05 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthe', '0005_remove_project_studentleadprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLeadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=255)),
                ('student_lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='userAuthe.studentlead')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=255)),
                ('supervisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='userAuthe.supervisor')),
            ],
        ),
    ]
