# Generated by Django 5.1.5 on 2025-02-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthe', '0006_studentleadprofile_supervisorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='department',
        ),
    ]
