# Generated by Django 5.1.5 on 2025-02-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthe', '0007_remove_supervisor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorprofile',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='studentlead',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentlead',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentlead',
            name='programme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='StudentLeadProfile',
        ),
        migrations.DeleteModel(
            name='SupervisorProfile',
        ),
    ]
