# Generated by Django 5.1.5 on 2025-02-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthe', '0008_remove_supervisorprofile_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
