# Generated by Django 5.1.5 on 2025-02-07 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthe', '0009_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='student_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='userAuthe.studentlead'),
        ),
    ]
