# Generated by Django 5.1.5 on 2025-02-08 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthe', '0011_projectmembers_studentproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembers',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userAuthe.studentproject'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmembers',
            unique_together={('user', 'first_name', 'last_name')},
        ),
    ]
