# Generated by Django 5.1.5 on 2025-02-08 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthe', '0012_projectmembers_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
