# Generated by Django 5.1.5 on 2025-02-11 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthe', '0013_alter_projectmembers_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectmembers',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='projectmembers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='projectmembers',
            name='project',
        ),
    ]
