# Generated by Django 5.1.5 on 2025-02-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthe', '0014_alter_projectmembers_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='StudentMember',
        ),
    ]
