# Generated by Django 5.1.5 on 2025-03-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthe', '0016_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
