# Generated by Django 5.1.5 on 2025-03-06 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectChapters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectchapters',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_chapters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), django.core.validators.MaxValueValidator(2097152)]),
        ),
    ]
