# Generated by Django 5.1.5 on 2025-03-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectChapters', '0002_projectchapters_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectchapters',
            name='file',
        ),
    ]
